name: amex-gpu
channels:
  - conda-forge
  # - nvidia
  # - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - spyder
  - matplotlib
  - pandas
  - jupyter
  - scikit-learn
  - ipython
  - pytest
  - tqdm
  - jupyterlab
  - cudatoolkit=11.8.0
  - pip
  - build
  - kaggle
  - pip:
      - nvidia-cudnn-cu11==8.6.0.163
      - tensorflow==2.12.*
