name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
    
jobs:
  build:
    strategy:
      matrix:
        include:

        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/amex

        - os: macos-latest
          label: osx-64
          prefix: /Users/runner/miniconda3/envs/amex
    
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: amex
          use-mamba: true


      - name: Cache lockfile
        uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: conda-${{ matrix.label }}-${{ hashFiles(format('environment.yml', matrix.label)) }}-${{ env.CACHE_NUMBER }}
        id: cache-conda

      - name: Update Conda Environment
        id: update-env
        run: |
          mamba env update --file environment.yml
        if: steps.cache-conda.outputs.cache-hit != 'true'

      - name: Install Project
        id: install-project
        run: |
          pip install .

      - name: Run tests
        run: pytest
